const data = {
  users: [
    {
      name: 'Jesse',
      email: ''
    }, {}],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/S1.jpg',
      price: 35000,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/S2.jpg',
      price: 34500,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirts',
      category: 'Shirts',
      image: '/images/S3.jpg',
      price: 30000,
      countInStock: 15,
      brand: 'Nike',
      rating: 5,
      numReviews: 4,
      description: 'High quality product',
    },
    {
      // _id: '4',
      name: 'Office Slim shirt',
      slug: 'office-slim-shirt',
      category: 'Shirts',
      image: '/images/S4.jpg',
      price: 19000,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 16,
      description: 'High quality product',
    },
    {
      // _id: '5',
      name: 'Adidas fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/P1.jpg',
      price: 16000,
      countInStock: 0,
      brand: 'Puma',
      rating: 2.0,
      numReviews: 13,
      description: 'High quality product',
    },
    {
      // _id: '6',
      name: 'Jean pant',
      slug: 'jean-pant',
      category: 'Pants',
      image: '/images/P2.jpg',
      price: 45000,
      countInStock: 25,
      brand: 'Puma',
      rating: 3.9,
      numReviews: 17,
      description: 'High quality product',
    },
    {
      // _id: '7',
      name: 'Khaki black pant',
      slug: 'khaki-black-pants',
      category: 'Pants',
      image: '/images/P3.jpg',
      price: 27000,
      countInStock: 40,
      brand: 'Khaki',
      rating: 4.5,
      numReviews: 9,
      description: 'High quality product',
    },
    {
      // _id: '8',
      name: 'Khaki pants',
      slug: 'khaki-pants',
      category: 'Pants',
      image: '/images/P4.jpg',
      price: 28000,
      countInStock: 15,
      brand: 'Khaki',
      rating: 2.5,
      numReviews: 8,
      description: 'High quality product',
    },
  ],
};

export default data;
