const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/S1.jpg',
      price: 35000,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/S2.jpg',
      price: 34500,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Nike Slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/S3.jpg',
      price: 40000,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality product',
    },
    {
      name: 'Adidas fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/S4.jpg',
      price: 30000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Adidas fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/P1.jpg',
      price: 30000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Adidas fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/P2.jpg',
      price: 30000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Adidas fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/P3.jpg',
      price: 30000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Khaki pants',
      slug: 'khaki-pants',
      category: 'Pants',
      image: '/images/P4.jpg',
      price: 30000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
};

export default data;
